<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control.proto

namespace Io\Axoniq\Axonserver\Grpc\Control;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Message containing details about the Client Application 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.control.ClientIdentification</code>
 */
class ClientIdentification extends \Google\Protobuf\Internal\Message
{
    /**
     * A unique identifier for this client instance. Is used to distinguish different instances of the same component 
     *
     * Generated from protobuf field <code>string client_id = 1;</code>
     */
    private $client_id = '';
    /**
     * The name of the component. Several instances of the same component should share this name 
     *
     * Generated from protobuf field <code>string component_name = 2;</code>
     */
    private $component_name = '';
    /**
     * Any tags associated with the client, which may provide hints and preferences for setting up connections 
     *
     * Generated from protobuf field <code>map<string, string> tags = 3;</code>
     */
    private $tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $client_id
     *           A unique identifier for this client instance. Is used to distinguish different instances of the same component 
     *     @type string $component_name
     *           The name of the component. Several instances of the same component should share this name 
     *     @type array|\Google\Protobuf\Internal\MapField $tags
     *           Any tags associated with the client, which may provide hints and preferences for setting up connections 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Control::initOnce();
        parent::__construct($data);
    }

    /**
     * A unique identifier for this client instance. Is used to distinguish different instances of the same component 
     *
     * Generated from protobuf field <code>string client_id = 1;</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * A unique identifier for this client instance. Is used to distinguish different instances of the same component 
     *
     * Generated from protobuf field <code>string client_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_id = $var;

        return $this;
    }

    /**
     * The name of the component. Several instances of the same component should share this name 
     *
     * Generated from protobuf field <code>string component_name = 2;</code>
     * @return string
     */
    public function getComponentName()
    {
        return $this->component_name;
    }

    /**
     * The name of the component. Several instances of the same component should share this name 
     *
     * Generated from protobuf field <code>string component_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setComponentName($var)
    {
        GPBUtil::checkString($var, True);
        $this->component_name = $var;

        return $this;
    }

    /**
     * Any tags associated with the client, which may provide hints and preferences for setting up connections 
     *
     * Generated from protobuf field <code>map<string, string> tags = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Any tags associated with the client, which may provide hints and preferences for setting up connections 
     *
     * Generated from protobuf field <code>map<string, string> tags = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

}

