<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control.proto

namespace Io\Axoniq\Axonserver\Grpc\Control;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Message providing reference to a Segment of an Event Processor 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.control.EventProcessorSegmentReference</code>
 */
class EventProcessorSegmentReference extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of the Event Processor 
     *
     * Generated from protobuf field <code>string processor_name = 1;</code>
     */
    private $processor_name = '';
    /**
     * The identifier of the Segment 
     *
     * Generated from protobuf field <code>int32 segment_identifier = 2;</code>
     */
    private $segment_identifier = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $processor_name
     *           The name of the Event Processor 
     *     @type int $segment_identifier
     *           The identifier of the Segment 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Control::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of the Event Processor 
     *
     * Generated from protobuf field <code>string processor_name = 1;</code>
     * @return string
     */
    public function getProcessorName()
    {
        return $this->processor_name;
    }

    /**
     * The name of the Event Processor 
     *
     * Generated from protobuf field <code>string processor_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProcessorName($var)
    {
        GPBUtil::checkString($var, True);
        $this->processor_name = $var;

        return $this;
    }

    /**
     * The identifier of the Segment 
     *
     * Generated from protobuf field <code>int32 segment_identifier = 2;</code>
     * @return int
     */
    public function getSegmentIdentifier()
    {
        return $this->segment_identifier;
    }

    /**
     * The identifier of the Segment 
     *
     * Generated from protobuf field <code>int32 segment_identifier = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSegmentIdentifier($var)
    {
        GPBUtil::checkInt32($var);
        $this->segment_identifier = $var;

        return $this;
    }

}

