<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control.proto

namespace Io\Axoniq\Axonserver\Grpc\Control;

if (false) {
    /**
     * This class is deprecated. Use Io\Axoniq\Axonserver\Grpc\Control\EventProcessorInfo\SegmentStatus instead.
     * @deprecated
     */
    class EventProcessorInfo_SegmentStatus {}
}
class_exists(EventProcessorInfo\SegmentStatus::class);
@trigger_error('Io\Axoniq\Axonserver\Grpc\Control\EventProcessorInfo_SegmentStatus is deprecated and will be removed in the next major release. Use Io\Axoniq\Axonserver\Grpc\Control\EventProcessorInfo\SegmentStatus instead', E_USER_DEPRECATED);

