<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control.proto

namespace Io\Axoniq\Axonserver\Grpc\Control;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Message providing reference to an Event Processor 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.control.EventProcessorReference</code>
 */
class EventProcessorReference extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of the Event Processor 
     *
     * Generated from protobuf field <code>string processor_name = 1;</code>
     */
    private $processor_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $processor_name
     *           The name of the Event Processor 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Control::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of the Event Processor 
     *
     * Generated from protobuf field <code>string processor_name = 1;</code>
     * @return string
     */
    public function getProcessorName()
    {
        return $this->processor_name;
    }

    /**
     * The name of the Event Processor 
     *
     * Generated from protobuf field <code>string processor_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProcessorName($var)
    {
        GPBUtil::checkString($var, True);
        $this->processor_name = $var;

        return $this;
    }

}

