<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control.proto

namespace Io\Axoniq\Axonserver\Grpc\Control;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Message containing connection information of the node to Connect with 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.control.PlatformInfo</code>
 */
class PlatformInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * The connection details of the node the client should connect with 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.control.NodeInfo primary = 1;</code>
     */
    private $primary = null;
    /**
     * Flag indicating that the connection may be reused to connect. When true, the client _may_ reuse the connection
     *established for the GetPlatformServer request for subsequent requests.
     *
     * Generated from protobuf field <code>bool same_connection = 2;</code>
     */
    private $same_connection = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Axoniq\Axonserver\Grpc\Control\NodeInfo $primary
     *           The connection details of the node the client should connect with 
     *     @type bool $same_connection
     *           Flag indicating that the connection may be reused to connect. When true, the client _may_ reuse the connection
     *          established for the GetPlatformServer request for subsequent requests.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Control::initOnce();
        parent::__construct($data);
    }

    /**
     * The connection details of the node the client should connect with 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.control.NodeInfo primary = 1;</code>
     * @return \Io\Axoniq\Axonserver\Grpc\Control\NodeInfo
     */
    public function getPrimary()
    {
        return $this->primary;
    }

    /**
     * The connection details of the node the client should connect with 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.control.NodeInfo primary = 1;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\Control\NodeInfo $var
     * @return $this
     */
    public function setPrimary($var)
    {
        GPBUtil::checkMessage($var, \Io\Axoniq\Axonserver\Grpc\Control\NodeInfo::class);
        $this->primary = $var;

        return $this;
    }

    /**
     * Flag indicating that the connection may be reused to connect. When true, the client _may_ reuse the connection
     *established for the GetPlatformServer request for subsequent requests.
     *
     * Generated from protobuf field <code>bool same_connection = 2;</code>
     * @return bool
     */
    public function getSameConnection()
    {
        return $this->same_connection;
    }

    /**
     * Flag indicating that the connection may be reused to connect. When true, the client _may_ reuse the connection
     *established for the GetPlatformServer request for subsequent requests.
     *
     * Generated from protobuf field <code>bool same_connection = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setSameConnection($var)
    {
        GPBUtil::checkBool($var);
        $this->same_connection = $var;

        return $this;
    }

}

