<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command.proto

namespace Io\Axoniq\Axonserver\Grpc\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A message representing a Command that needs to be routed to a component capable of handling it 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.command.Command</code>
 */
class Command extends \Google\Protobuf\Internal\Message
{
    /**
     * The unique identifier of the Command Message 
     *
     * Generated from protobuf field <code>string message_identifier = 1;</code>
     */
    private $message_identifier = '';
    /**
     * The name of the command, used for routing it to a destination capable of handling it 
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * The time at which the command was dispatched 
     *
     * Generated from protobuf field <code>int64 timestamp = 3;</code>
     */
    private $timestamp = 0;
    /**
     * The payload of the Command, providing details on the instructions for the recipient 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.SerializedObject payload = 4;</code>
     */
    private $payload = null;
    /**
     * Meta Data entries of the Command Message, providing contextual information to the recipient 
     *
     * Generated from protobuf field <code>map<string, .io.axoniq.axonserver.grpc.MetaDataValue> meta_data = 5;</code>
     */
    private $meta_data;
    /**
     * Instructions for AxonServer when routing this Command Message 
     *
     * Generated from protobuf field <code>repeated .io.axoniq.axonserver.grpc.ProcessingInstruction processing_instructions = 6;</code>
     */
    private $processing_instructions;
    /**
     * The unique identifier of the component dispatching this message 
     *
     * Generated from protobuf field <code>string client_id = 7;</code>
     */
    private $client_id = '';
    /**
     * The name/type of the component dispatching this message 
     *
     * Generated from protobuf field <code>string component_name = 8;</code>
     */
    private $component_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message_identifier
     *           The unique identifier of the Command Message 
     *     @type string $name
     *           The name of the command, used for routing it to a destination capable of handling it 
     *     @type int|string $timestamp
     *           The time at which the command was dispatched 
     *     @type \Io\Axoniq\Axonserver\Grpc\SerializedObject $payload
     *           The payload of the Command, providing details on the instructions for the recipient 
     *     @type array|\Google\Protobuf\Internal\MapField $meta_data
     *           Meta Data entries of the Command Message, providing contextual information to the recipient 
     *     @type \Io\Axoniq\Axonserver\Grpc\ProcessingInstruction[]|\Google\Protobuf\Internal\RepeatedField $processing_instructions
     *           Instructions for AxonServer when routing this Command Message 
     *     @type string $client_id
     *           The unique identifier of the component dispatching this message 
     *     @type string $component_name
     *           The name/type of the component dispatching this message 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Command::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique identifier of the Command Message 
     *
     * Generated from protobuf field <code>string message_identifier = 1;</code>
     * @return string
     */
    public function getMessageIdentifier()
    {
        return $this->message_identifier;
    }

    /**
     * The unique identifier of the Command Message 
     *
     * Generated from protobuf field <code>string message_identifier = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->message_identifier = $var;

        return $this;
    }

    /**
     * The name of the command, used for routing it to a destination capable of handling it 
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the command, used for routing it to a destination capable of handling it 
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * The time at which the command was dispatched 
     *
     * Generated from protobuf field <code>int64 timestamp = 3;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * The time at which the command was dispatched 
     *
     * Generated from protobuf field <code>int64 timestamp = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * The payload of the Command, providing details on the instructions for the recipient 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.SerializedObject payload = 4;</code>
     * @return \Io\Axoniq\Axonserver\Grpc\SerializedObject
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * The payload of the Command, providing details on the instructions for the recipient 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.SerializedObject payload = 4;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\SerializedObject $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkMessage($var, \Io\Axoniq\Axonserver\Grpc\SerializedObject::class);
        $this->payload = $var;

        return $this;
    }

    /**
     * Meta Data entries of the Command Message, providing contextual information to the recipient 
     *
     * Generated from protobuf field <code>map<string, .io.axoniq.axonserver.grpc.MetaDataValue> meta_data = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMetaData()
    {
        return $this->meta_data;
    }

    /**
     * Meta Data entries of the Command Message, providing contextual information to the recipient 
     *
     * Generated from protobuf field <code>map<string, .io.axoniq.axonserver.grpc.MetaDataValue> meta_data = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMetaData($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Axoniq\Axonserver\Grpc\MetaDataValue::class);
        $this->meta_data = $arr;

        return $this;
    }

    /**
     * Instructions for AxonServer when routing this Command Message 
     *
     * Generated from protobuf field <code>repeated .io.axoniq.axonserver.grpc.ProcessingInstruction processing_instructions = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProcessingInstructions()
    {
        return $this->processing_instructions;
    }

    /**
     * Instructions for AxonServer when routing this Command Message 
     *
     * Generated from protobuf field <code>repeated .io.axoniq.axonserver.grpc.ProcessingInstruction processing_instructions = 6;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\ProcessingInstruction[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProcessingInstructions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Axoniq\Axonserver\Grpc\ProcessingInstruction::class);
        $this->processing_instructions = $arr;

        return $this;
    }

    /**
     * The unique identifier of the component dispatching this message 
     *
     * Generated from protobuf field <code>string client_id = 7;</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * The unique identifier of the component dispatching this message 
     *
     * Generated from protobuf field <code>string client_id = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_id = $var;

        return $this;
    }

    /**
     * The name/type of the component dispatching this message 
     *
     * Generated from protobuf field <code>string component_name = 8;</code>
     * @return string
     */
    public function getComponentName()
    {
        return $this->component_name;
    }

    /**
     * The name/type of the component dispatching this message 
     *
     * Generated from protobuf field <code>string component_name = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setComponentName($var)
    {
        GPBUtil::checkString($var, True);
        $this->component_name = $var;

        return $this;
    }

}

