<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Io\Axoniq\Axonserver\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Message containing details of an error 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.ErrorMessage</code>
 */
class ErrorMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * A human readable message explaining the error 
     *
     * Generated from protobuf field <code>string message = 1;</code>
     */
    private $message = '';
    /**
     * A description of the location (client component, server) where the error occurred 
     *
     * Generated from protobuf field <code>string location = 2;</code>
     */
    private $location = '';
    /**
     * A collection of messages providing more details about root causes of the error 
     *
     * Generated from protobuf field <code>repeated string details = 3;</code>
     */
    private $details;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message
     *           A human readable message explaining the error 
     *     @type string $location
     *           A description of the location (client component, server) where the error occurred 
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $details
     *           A collection of messages providing more details about root causes of the error 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * A human readable message explaining the error 
     *
     * Generated from protobuf field <code>string message = 1;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * A human readable message explaining the error 
     *
     * Generated from protobuf field <code>string message = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * A description of the location (client component, server) where the error occurred 
     *
     * Generated from protobuf field <code>string location = 2;</code>
     * @return string
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * A description of the location (client component, server) where the error occurred 
     *
     * Generated from protobuf field <code>string location = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkString($var, True);
        $this->location = $var;

        return $this;
    }

    /**
     * A collection of messages providing more details about root causes of the error 
     *
     * Generated from protobuf field <code>repeated string details = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * A collection of messages providing more details about root causes of the error 
     *
     * Generated from protobuf field <code>repeated string details = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDetails($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->details = $arr;

        return $this;
    }

}

