<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Io\Axoniq\Axonserver\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The value of a MetaData entry. 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.MetaDataValue</code>
 */
class MetaDataValue extends \Google\Protobuf\Internal\Message
{
    protected $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $text_value
     *           The text value of the Meta Data entry. 
     *     @type int|string $number_value
     *           The numeric value of the Meta Data entry. 
     *     @type bool $boolean_value
     *           The boolean value of the Meta Data entry. 
     *     @type float $double_value
     *           The floating point value of the Meta Data entry. 
     *     @type \Io\Axoniq\Axonserver\Grpc\SerializedObject $bytes_value
     *           The binary value of the Meta Data entry. 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * The text value of the Meta Data entry. 
     *
     * Generated from protobuf field <code>string text_value = 1;</code>
     * @return string
     */
    public function getTextValue()
    {
        return $this->readOneof(1);
    }

    /**
     * The text value of the Meta Data entry. 
     *
     * Generated from protobuf field <code>string text_value = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTextValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * The numeric value of the Meta Data entry. 
     *
     * Generated from protobuf field <code>sint64 number_value = 2;</code>
     * @return int|string
     */
    public function getNumberValue()
    {
        return $this->readOneof(2);
    }

    /**
     * The numeric value of the Meta Data entry. 
     *
     * Generated from protobuf field <code>sint64 number_value = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNumberValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * The boolean value of the Meta Data entry. 
     *
     * Generated from protobuf field <code>bool boolean_value = 3;</code>
     * @return bool
     */
    public function getBooleanValue()
    {
        return $this->readOneof(3);
    }

    /**
     * The boolean value of the Meta Data entry. 
     *
     * Generated from protobuf field <code>bool boolean_value = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setBooleanValue($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * The floating point value of the Meta Data entry. 
     *
     * Generated from protobuf field <code>double double_value = 4;</code>
     * @return float
     */
    public function getDoubleValue()
    {
        return $this->readOneof(4);
    }

    /**
     * The floating point value of the Meta Data entry. 
     *
     * Generated from protobuf field <code>double double_value = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setDoubleValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * The binary value of the Meta Data entry. 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.SerializedObject bytes_value = 5;</code>
     * @return \Io\Axoniq\Axonserver\Grpc\SerializedObject
     */
    public function getBytesValue()
    {
        return $this->readOneof(5);
    }

    /**
     * The binary value of the Meta Data entry. 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.SerializedObject bytes_value = 5;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\SerializedObject $var
     * @return $this
     */
    public function setBytesValue($var)
    {
        GPBUtil::checkMessage($var, \Io\Axoniq\Axonserver\Grpc\SerializedObject::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getData()
    {
        return $this->whichOneof("data");
    }

}

