<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Io\Axoniq\Axonserver\Grpc;

/**
 * An enumeration of possible keys for processing instructions. 
 *
 * Protobuf type <code>io.axoniq.axonserver.grpc.ProcessingKey</code>
 */
class ProcessingKey
{
    /**
     * key indicating that the attached value should be used for consistent routing. 
     *
     * Generated from protobuf enum <code>ROUTING_KEY = 0;</code>
     */
    const ROUTING_KEY = 0;
    /**
     * key indicating that the attached value indicates relative priority of this message. 
     *
     * Generated from protobuf enum <code>PRIORITY = 1;</code>
     */
    const PRIORITY = 1;
    /**
     * key indicating that the accompanied message has a finite validity. The attached value contains the number of milliseconds. 
     *
     * Generated from protobuf enum <code>TIMEOUT = 2;</code>
     */
    const TIMEOUT = 2;
    /**
     * key indicating that the requester expects at most the given number of results from this message. Use -1 for unlimited. 
     *
     * Generated from protobuf enum <code>NR_OF_RESULTS = 3;</code>
     */
    const NR_OF_RESULTS = 3;
}

