<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Io\Axoniq\Axonserver\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * An instruction for routing components when routing or processing a message. 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.ProcessingInstruction</code>
 */
class ProcessingInstruction extends \Google\Protobuf\Internal\Message
{
    /**
     * The type of processing message. 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.ProcessingKey key = 1;</code>
     */
    private $key = 0;
    /**
     * The value associated with the processing key.  
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.MetaDataValue value = 2;</code>
     */
    private $value = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $key
     *           The type of processing message. 
     *     @type \Io\Axoniq\Axonserver\Grpc\MetaDataValue $value
     *           The value associated with the processing key.  
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * The type of processing message. 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.ProcessingKey key = 1;</code>
     * @return int
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * The type of processing message. 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.ProcessingKey key = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkEnum($var, \Io\Axoniq\Axonserver\Grpc\ProcessingKey::class);
        $this->key = $var;

        return $this;
    }

    /**
     * The value associated with the processing key.  
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.MetaDataValue value = 2;</code>
     * @return \Io\Axoniq\Axonserver\Grpc\MetaDataValue
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * The value associated with the processing key.  
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.MetaDataValue value = 2;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\MetaDataValue $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkMessage($var, \Io\Axoniq\Axonserver\Grpc\MetaDataValue::class);
        $this->value = $var;

        return $this;
    }

}

