<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Io\Axoniq\Axonserver\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Describes a serialized object 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.SerializedObject</code>
 */
class SerializedObject extends \Google\Protobuf\Internal\Message
{
    /**
     * The type identifier of the serialized object. 
     *
     * Generated from protobuf field <code>string type = 1;</code>
     */
    private $type = '';
    /**
     * The revision of the serialized form of the given type. 
     *
     * Generated from protobuf field <code>string revision = 2;</code>
     */
    private $revision = '';
    /**
     * The actual data representing the object in serialized form. 
     *
     * Generated from protobuf field <code>bytes data = 3;</code>
     */
    private $data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *           The type identifier of the serialized object. 
     *     @type string $revision
     *           The revision of the serialized form of the given type. 
     *     @type string $data
     *           The actual data representing the object in serialized form. 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * The type identifier of the serialized object. 
     *
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * The type identifier of the serialized object. 
     *
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * The revision of the serialized form of the given type. 
     *
     * Generated from protobuf field <code>string revision = 2;</code>
     * @return string
     */
    public function getRevision()
    {
        return $this->revision;
    }

    /**
     * The revision of the serialized form of the given type. 
     *
     * Generated from protobuf field <code>string revision = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRevision($var)
    {
        GPBUtil::checkString($var, True);
        $this->revision = $var;

        return $this;
    }

    /**
     * The actual data representing the object in serialized form. 
     *
     * Generated from protobuf field <code>bytes data = 3;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * The actual data representing the object in serialized form. 
     *
     * Generated from protobuf field <code>bytes data = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

}

