<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace Io\Axoniq\Axonserver\Grpc\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Message that represents the Response to a Query 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.query.QueryResponse</code>
 */
class QueryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The unique identifier of the Response Message 
     *
     * Generated from protobuf field <code>string message_identifier = 1;</code>
     */
    private $message_identifier = '';
    /**
     * An Error Code identifying the type of error, if any 
     *
     * Generated from protobuf field <code>string error_code = 2;</code>
     */
    private $error_code = '';
    /**
     * A detailed description of the error, if any 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.ErrorMessage error_message = 3;</code>
     */
    private $error_message = null;
    /**
     * The Payload of the Response Message 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.SerializedObject payload = 4;</code>
     */
    private $payload = null;
    /**
     * Any Meta Data describing the context of the Response Message 
     *
     * Generated from protobuf field <code>map<string, .io.axoniq.axonserver.grpc.MetaDataValue> meta_data = 5;</code>
     */
    private $meta_data;
    /**
     * Any instructions for components Routing or Handling the Response Message 
     *
     * Generated from protobuf field <code>repeated .io.axoniq.axonserver.grpc.ProcessingInstruction processing_instructions = 6;</code>
     */
    private $processing_instructions;
    /**
     * The unique identifier of the Query to which this is a response 
     *
     * Generated from protobuf field <code>string request_identifier = 7;</code>
     */
    private $request_identifier = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message_identifier
     *           The unique identifier of the Response Message 
     *     @type string $error_code
     *           An Error Code identifying the type of error, if any 
     *     @type \Io\Axoniq\Axonserver\Grpc\ErrorMessage $error_message
     *           A detailed description of the error, if any 
     *     @type \Io\Axoniq\Axonserver\Grpc\SerializedObject $payload
     *           The Payload of the Response Message 
     *     @type array|\Google\Protobuf\Internal\MapField $meta_data
     *           Any Meta Data describing the context of the Response Message 
     *     @type \Io\Axoniq\Axonserver\Grpc\ProcessingInstruction[]|\Google\Protobuf\Internal\RepeatedField $processing_instructions
     *           Any instructions for components Routing or Handling the Response Message 
     *     @type string $request_identifier
     *           The unique identifier of the Query to which this is a response 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique identifier of the Response Message 
     *
     * Generated from protobuf field <code>string message_identifier = 1;</code>
     * @return string
     */
    public function getMessageIdentifier()
    {
        return $this->message_identifier;
    }

    /**
     * The unique identifier of the Response Message 
     *
     * Generated from protobuf field <code>string message_identifier = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->message_identifier = $var;

        return $this;
    }

    /**
     * An Error Code identifying the type of error, if any 
     *
     * Generated from protobuf field <code>string error_code = 2;</code>
     * @return string
     */
    public function getErrorCode()
    {
        return $this->error_code;
    }

    /**
     * An Error Code identifying the type of error, if any 
     *
     * Generated from protobuf field <code>string error_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_code = $var;

        return $this;
    }

    /**
     * A detailed description of the error, if any 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.ErrorMessage error_message = 3;</code>
     * @return \Io\Axoniq\Axonserver\Grpc\ErrorMessage
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    /**
     * A detailed description of the error, if any 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.ErrorMessage error_message = 3;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\ErrorMessage $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkMessage($var, \Io\Axoniq\Axonserver\Grpc\ErrorMessage::class);
        $this->error_message = $var;

        return $this;
    }

    /**
     * The Payload of the Response Message 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.SerializedObject payload = 4;</code>
     * @return \Io\Axoniq\Axonserver\Grpc\SerializedObject
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * The Payload of the Response Message 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.SerializedObject payload = 4;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\SerializedObject $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkMessage($var, \Io\Axoniq\Axonserver\Grpc\SerializedObject::class);
        $this->payload = $var;

        return $this;
    }

    /**
     * Any Meta Data describing the context of the Response Message 
     *
     * Generated from protobuf field <code>map<string, .io.axoniq.axonserver.grpc.MetaDataValue> meta_data = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMetaData()
    {
        return $this->meta_data;
    }

    /**
     * Any Meta Data describing the context of the Response Message 
     *
     * Generated from protobuf field <code>map<string, .io.axoniq.axonserver.grpc.MetaDataValue> meta_data = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMetaData($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Axoniq\Axonserver\Grpc\MetaDataValue::class);
        $this->meta_data = $arr;

        return $this;
    }

    /**
     * Any instructions for components Routing or Handling the Response Message 
     *
     * Generated from protobuf field <code>repeated .io.axoniq.axonserver.grpc.ProcessingInstruction processing_instructions = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProcessingInstructions()
    {
        return $this->processing_instructions;
    }

    /**
     * Any instructions for components Routing or Handling the Response Message 
     *
     * Generated from protobuf field <code>repeated .io.axoniq.axonserver.grpc.ProcessingInstruction processing_instructions = 6;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\ProcessingInstruction[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProcessingInstructions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Axoniq\Axonserver\Grpc\ProcessingInstruction::class);
        $this->processing_instructions = $arr;

        return $this;
    }

    /**
     * The unique identifier of the Query to which this is a response 
     *
     * Generated from protobuf field <code>string request_identifier = 7;</code>
     * @return string
     */
    public function getRequestIdentifier()
    {
        return $this->request_identifier;
    }

    /**
     * The unique identifier of the Query to which this is a response 
     *
     * Generated from protobuf field <code>string request_identifier = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->request_identifier = $var;

        return $this;
    }

}

