<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace Io\Axoniq\Axonserver\Grpc\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A message containing an Update of a Query Subscription Response 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.query.QueryUpdate</code>
 */
class QueryUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * The unique identifier of this Update 
     *
     * Generated from protobuf field <code>string message_identifier = 2;</code>
     */
    private $message_identifier = '';
    /**
     * The object representing the Update 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.SerializedObject payload = 3;</code>
     */
    private $payload = null;
    /**
     * Meta Data providing contextual information of the Update 
     *
     * Generated from protobuf field <code>map<string, .io.axoniq.axonserver.grpc.MetaDataValue> meta_data = 4;</code>
     */
    private $meta_data;
    /**
     * The identifier of the Client instance providing the Update 
     *
     * Generated from protobuf field <code>string client_id = 5;</code>
     */
    private $client_id = '';
    /**
     * The Component Name of the Client providing the Update 
     *
     * Generated from protobuf field <code>string component_name = 6;</code>
     */
    private $component_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message_identifier
     *           The unique identifier of this Update 
     *     @type \Io\Axoniq\Axonserver\Grpc\SerializedObject $payload
     *           The object representing the Update 
     *     @type array|\Google\Protobuf\Internal\MapField $meta_data
     *           Meta Data providing contextual information of the Update 
     *     @type string $client_id
     *           The identifier of the Client instance providing the Update 
     *     @type string $component_name
     *           The Component Name of the Client providing the Update 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique identifier of this Update 
     *
     * Generated from protobuf field <code>string message_identifier = 2;</code>
     * @return string
     */
    public function getMessageIdentifier()
    {
        return $this->message_identifier;
    }

    /**
     * The unique identifier of this Update 
     *
     * Generated from protobuf field <code>string message_identifier = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->message_identifier = $var;

        return $this;
    }

    /**
     * The object representing the Update 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.SerializedObject payload = 3;</code>
     * @return \Io\Axoniq\Axonserver\Grpc\SerializedObject
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * The object representing the Update 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.SerializedObject payload = 3;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\SerializedObject $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkMessage($var, \Io\Axoniq\Axonserver\Grpc\SerializedObject::class);
        $this->payload = $var;

        return $this;
    }

    /**
     * Meta Data providing contextual information of the Update 
     *
     * Generated from protobuf field <code>map<string, .io.axoniq.axonserver.grpc.MetaDataValue> meta_data = 4;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMetaData()
    {
        return $this->meta_data;
    }

    /**
     * Meta Data providing contextual information of the Update 
     *
     * Generated from protobuf field <code>map<string, .io.axoniq.axonserver.grpc.MetaDataValue> meta_data = 4;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMetaData($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Axoniq\Axonserver\Grpc\MetaDataValue::class);
        $this->meta_data = $arr;

        return $this;
    }

    /**
     * The identifier of the Client instance providing the Update 
     *
     * Generated from protobuf field <code>string client_id = 5;</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * The identifier of the Client instance providing the Update 
     *
     * Generated from protobuf field <code>string client_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_id = $var;

        return $this;
    }

    /**
     * The Component Name of the Client providing the Update 
     *
     * Generated from protobuf field <code>string component_name = 6;</code>
     * @return string
     */
    public function getComponentName()
    {
        return $this->component_name;
    }

    /**
     * The Component Name of the Client providing the Update 
     *
     * Generated from protobuf field <code>string component_name = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setComponentName($var)
    {
        GPBUtil::checkString($var, True);
        $this->component_name = $var;

        return $this;
    }

}

