<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace Io\Axoniq\Axonserver\Grpc\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Message indicating that an Error occurred and that no Updates will be sent for a Subscription Query 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.query.QueryUpdateCompleteExceptionally</code>
 */
class QueryUpdateCompleteExceptionally extends \Google\Protobuf\Internal\Message
{
    /**
     * The identifier of the Client instance providing the Update 
     *
     * Generated from protobuf field <code>string client_id = 2;</code>
     */
    private $client_id = '';
    /**
     * The Component Name of the Client providing the Update 
     *
     * Generated from protobuf field <code>string component_name = 3;</code>
     */
    private $component_name = '';
    /**
     * The Code describing the type of Error that occurred 
     *
     * Generated from protobuf field <code>string error_code = 5;</code>
     */
    private $error_code = '';
    /**
     * A detailed description of the error, if available 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.ErrorMessage error_message = 6;</code>
     */
    private $error_message = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $client_id
     *           The identifier of the Client instance providing the Update 
     *     @type string $component_name
     *           The Component Name of the Client providing the Update 
     *     @type string $error_code
     *           The Code describing the type of Error that occurred 
     *     @type \Io\Axoniq\Axonserver\Grpc\ErrorMessage $error_message
     *           A detailed description of the error, if available 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * The identifier of the Client instance providing the Update 
     *
     * Generated from protobuf field <code>string client_id = 2;</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * The identifier of the Client instance providing the Update 
     *
     * Generated from protobuf field <code>string client_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_id = $var;

        return $this;
    }

    /**
     * The Component Name of the Client providing the Update 
     *
     * Generated from protobuf field <code>string component_name = 3;</code>
     * @return string
     */
    public function getComponentName()
    {
        return $this->component_name;
    }

    /**
     * The Component Name of the Client providing the Update 
     *
     * Generated from protobuf field <code>string component_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setComponentName($var)
    {
        GPBUtil::checkString($var, True);
        $this->component_name = $var;

        return $this;
    }

    /**
     * The Code describing the type of Error that occurred 
     *
     * Generated from protobuf field <code>string error_code = 5;</code>
     * @return string
     */
    public function getErrorCode()
    {
        return $this->error_code;
    }

    /**
     * The Code describing the type of Error that occurred 
     *
     * Generated from protobuf field <code>string error_code = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_code = $var;

        return $this;
    }

    /**
     * A detailed description of the error, if available 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.ErrorMessage error_message = 6;</code>
     * @return \Io\Axoniq\Axonserver\Grpc\ErrorMessage
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    /**
     * A detailed description of the error, if available 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.ErrorMessage error_message = 6;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\ErrorMessage $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkMessage($var, \Io\Axoniq\Axonserver\Grpc\ErrorMessage::class);
        $this->error_message = $var;

        return $this;
    }

}

