<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace Io\Axoniq\Axonserver\Grpc\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Message representing an incoming Query 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.query.QueryRequest</code>
 */
class QueryRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The message ID of the incoming Query 
     *
     * Generated from protobuf field <code>string message_identifier = 1;</code>
     */
    private $message_identifier = '';
    /**
     * The name of the Query to execute 
     *
     * Generated from protobuf field <code>string query = 2;</code>
     */
    private $query = '';
    /**
     * The timestamp of the Query creation 
     *
     * Generated from protobuf field <code>int64 timestamp = 3;</code>
     */
    private $timestamp = 0;
    /**
     * A payload accompanying the Query 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.SerializedObject payload = 4;</code>
     */
    private $payload = null;
    /**
     * Meta Data providing contextual information of the Query 
     *
     * Generated from protobuf field <code>map<string, .io.axoniq.axonserver.grpc.MetaDataValue> meta_data = 5;</code>
     */
    private $meta_data;
    /**
     * An object describing the expectations of the Response Type 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.SerializedObject response_type = 6;</code>
     */
    private $response_type = null;
    /**
     * Any instructions for components Routing or Handling the Query 
     *
     * Generated from protobuf field <code>repeated .io.axoniq.axonserver.grpc.ProcessingInstruction processing_instructions = 7;</code>
     */
    private $processing_instructions;
    /**
     * The unique identifier of the client instance dispatching the query 
     *
     * Generated from protobuf field <code>string client_id = 8;</code>
     */
    private $client_id = '';
    /**
     * The Name of the Component dispatching the query 
     *
     * Generated from protobuf field <code>string component_name = 9;</code>
     */
    private $component_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message_identifier
     *           The message ID of the incoming Query 
     *     @type string $query
     *           The name of the Query to execute 
     *     @type int|string $timestamp
     *           The timestamp of the Query creation 
     *     @type \Io\Axoniq\Axonserver\Grpc\SerializedObject $payload
     *           A payload accompanying the Query 
     *     @type array|\Google\Protobuf\Internal\MapField $meta_data
     *           Meta Data providing contextual information of the Query 
     *     @type \Io\Axoniq\Axonserver\Grpc\SerializedObject $response_type
     *           An object describing the expectations of the Response Type 
     *     @type \Io\Axoniq\Axonserver\Grpc\ProcessingInstruction[]|\Google\Protobuf\Internal\RepeatedField $processing_instructions
     *           Any instructions for components Routing or Handling the Query 
     *     @type string $client_id
     *           The unique identifier of the client instance dispatching the query 
     *     @type string $component_name
     *           The Name of the Component dispatching the query 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * The message ID of the incoming Query 
     *
     * Generated from protobuf field <code>string message_identifier = 1;</code>
     * @return string
     */
    public function getMessageIdentifier()
    {
        return $this->message_identifier;
    }

    /**
     * The message ID of the incoming Query 
     *
     * Generated from protobuf field <code>string message_identifier = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->message_identifier = $var;

        return $this;
    }

    /**
     * The name of the Query to execute 
     *
     * Generated from protobuf field <code>string query = 2;</code>
     * @return string
     */
    public function getQuery()
    {
        return $this->query;
    }

    /**
     * The name of the Query to execute 
     *
     * Generated from protobuf field <code>string query = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setQuery($var)
    {
        GPBUtil::checkString($var, True);
        $this->query = $var;

        return $this;
    }

    /**
     * The timestamp of the Query creation 
     *
     * Generated from protobuf field <code>int64 timestamp = 3;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * The timestamp of the Query creation 
     *
     * Generated from protobuf field <code>int64 timestamp = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * A payload accompanying the Query 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.SerializedObject payload = 4;</code>
     * @return \Io\Axoniq\Axonserver\Grpc\SerializedObject
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * A payload accompanying the Query 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.SerializedObject payload = 4;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\SerializedObject $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkMessage($var, \Io\Axoniq\Axonserver\Grpc\SerializedObject::class);
        $this->payload = $var;

        return $this;
    }

    /**
     * Meta Data providing contextual information of the Query 
     *
     * Generated from protobuf field <code>map<string, .io.axoniq.axonserver.grpc.MetaDataValue> meta_data = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMetaData()
    {
        return $this->meta_data;
    }

    /**
     * Meta Data providing contextual information of the Query 
     *
     * Generated from protobuf field <code>map<string, .io.axoniq.axonserver.grpc.MetaDataValue> meta_data = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMetaData($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Axoniq\Axonserver\Grpc\MetaDataValue::class);
        $this->meta_data = $arr;

        return $this;
    }

    /**
     * An object describing the expectations of the Response Type 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.SerializedObject response_type = 6;</code>
     * @return \Io\Axoniq\Axonserver\Grpc\SerializedObject
     */
    public function getResponseType()
    {
        return $this->response_type;
    }

    /**
     * An object describing the expectations of the Response Type 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.SerializedObject response_type = 6;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\SerializedObject $var
     * @return $this
     */
    public function setResponseType($var)
    {
        GPBUtil::checkMessage($var, \Io\Axoniq\Axonserver\Grpc\SerializedObject::class);
        $this->response_type = $var;

        return $this;
    }

    /**
     * Any instructions for components Routing or Handling the Query 
     *
     * Generated from protobuf field <code>repeated .io.axoniq.axonserver.grpc.ProcessingInstruction processing_instructions = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProcessingInstructions()
    {
        return $this->processing_instructions;
    }

    /**
     * Any instructions for components Routing or Handling the Query 
     *
     * Generated from protobuf field <code>repeated .io.axoniq.axonserver.grpc.ProcessingInstruction processing_instructions = 7;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\ProcessingInstruction[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProcessingInstructions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Axoniq\Axonserver\Grpc\ProcessingInstruction::class);
        $this->processing_instructions = $arr;

        return $this;
    }

    /**
     * The unique identifier of the client instance dispatching the query 
     *
     * Generated from protobuf field <code>string client_id = 8;</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * The unique identifier of the client instance dispatching the query 
     *
     * Generated from protobuf field <code>string client_id = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_id = $var;

        return $this;
    }

    /**
     * The Name of the Component dispatching the query 
     *
     * Generated from protobuf field <code>string component_name = 9;</code>
     * @return string
     */
    public function getComponentName()
    {
        return $this->component_name;
    }

    /**
     * The Name of the Component dispatching the query 
     *
     * Generated from protobuf field <code>string component_name = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setComponentName($var)
    {
        GPBUtil::checkString($var, True);
        $this->component_name = $var;

        return $this;
    }

}

