<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace Io\Axoniq\Axonserver\Grpc\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Message indicating that all relevant Updates have been sent for a Subscription Query, and that no further Updates are available 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.query.QueryUpdateComplete</code>
 */
class QueryUpdateComplete extends \Google\Protobuf\Internal\Message
{
    /**
     * The identifier of the Client instance providing the Update 
     *
     * Generated from protobuf field <code>string client_id = 2;</code>
     */
    private $client_id = '';
    /**
     * The Component Name of the Client providing the Update 
     *
     * Generated from protobuf field <code>string component_name = 3;</code>
     */
    private $component_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $client_id
     *           The identifier of the Client instance providing the Update 
     *     @type string $component_name
     *           The Component Name of the Client providing the Update 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * The identifier of the Client instance providing the Update 
     *
     * Generated from protobuf field <code>string client_id = 2;</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * The identifier of the Client instance providing the Update 
     *
     * Generated from protobuf field <code>string client_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_id = $var;

        return $this;
    }

    /**
     * The Component Name of the Client providing the Update 
     *
     * Generated from protobuf field <code>string component_name = 3;</code>
     * @return string
     */
    public function getComponentName()
    {
        return $this->component_name;
    }

    /**
     * The Component Name of the Client providing the Update 
     *
     * Generated from protobuf field <code>string component_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setComponentName($var)
    {
        GPBUtil::checkString($var, True);
        $this->component_name = $var;

        return $this;
    }

}

