<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace Io\Axoniq\Axonserver\Grpc\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Message that represents a Subscription Query 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.query.SubscriptionQuery</code>
 */
class SubscriptionQuery extends \Google\Protobuf\Internal\Message
{
    /**
     * A unique identifier for this subscription 
     *
     * Generated from protobuf field <code>string subscription_identifier = 1;</code>
     */
    private $subscription_identifier = '';
    /**
     * The number of messages the Server may send before needing to await additional permits 
     *
     * Generated from protobuf field <code>int64 number_of_permits = 2;</code>
     */
    private $number_of_permits = 0;
    /**
     * The Query describing the desire for information 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.query.QueryRequest query_request = 3;</code>
     */
    private $query_request = null;
    /**
     * A description of the type of Object expected as Update Responses 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.SerializedObject update_response_type = 4;</code>
     */
    private $update_response_type = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $subscription_identifier
     *           A unique identifier for this subscription 
     *     @type int|string $number_of_permits
     *           The number of messages the Server may send before needing to await additional permits 
     *     @type \Io\Axoniq\Axonserver\Grpc\Query\QueryRequest $query_request
     *           The Query describing the desire for information 
     *     @type \Io\Axoniq\Axonserver\Grpc\SerializedObject $update_response_type
     *           A description of the type of Object expected as Update Responses 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * A unique identifier for this subscription 
     *
     * Generated from protobuf field <code>string subscription_identifier = 1;</code>
     * @return string
     */
    public function getSubscriptionIdentifier()
    {
        return $this->subscription_identifier;
    }

    /**
     * A unique identifier for this subscription 
     *
     * Generated from protobuf field <code>string subscription_identifier = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSubscriptionIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->subscription_identifier = $var;

        return $this;
    }

    /**
     * The number of messages the Server may send before needing to await additional permits 
     *
     * Generated from protobuf field <code>int64 number_of_permits = 2;</code>
     * @return int|string
     */
    public function getNumberOfPermits()
    {
        return $this->number_of_permits;
    }

    /**
     * The number of messages the Server may send before needing to await additional permits 
     *
     * Generated from protobuf field <code>int64 number_of_permits = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNumberOfPermits($var)
    {
        GPBUtil::checkInt64($var);
        $this->number_of_permits = $var;

        return $this;
    }

    /**
     * The Query describing the desire for information 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.query.QueryRequest query_request = 3;</code>
     * @return \Io\Axoniq\Axonserver\Grpc\Query\QueryRequest
     */
    public function getQueryRequest()
    {
        return $this->query_request;
    }

    /**
     * The Query describing the desire for information 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.query.QueryRequest query_request = 3;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\Query\QueryRequest $var
     * @return $this
     */
    public function setQueryRequest($var)
    {
        GPBUtil::checkMessage($var, \Io\Axoniq\Axonserver\Grpc\Query\QueryRequest::class);
        $this->query_request = $var;

        return $this;
    }

    /**
     * A description of the type of Object expected as Update Responses 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.SerializedObject update_response_type = 4;</code>
     * @return \Io\Axoniq\Axonserver\Grpc\SerializedObject
     */
    public function getUpdateResponseType()
    {
        return $this->update_response_type;
    }

    /**
     * A description of the type of Object expected as Update Responses 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.SerializedObject update_response_type = 4;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\SerializedObject $var
     * @return $this
     */
    public function setUpdateResponseType($var)
    {
        GPBUtil::checkMessage($var, \Io\Axoniq\Axonserver\Grpc\SerializedObject::class);
        $this->update_response_type = $var;

        return $this;
    }

}

