<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace Io\Axoniq\Axonserver\Grpc\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Represents a Response Message for a Subscription Query 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.query.SubscriptionQueryResponse</code>
 */
class SubscriptionQueryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The unique identifier for this message 
     *
     * Generated from protobuf field <code>string message_identifier = 1;</code>
     */
    private $message_identifier = '';
    /**
     * The identifier of the subscription query this is a response for 
     *
     * Generated from protobuf field <code>string subscription_identifier = 2;</code>
     */
    private $subscription_identifier = '';
    protected $response;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message_identifier
     *           The unique identifier for this message 
     *     @type string $subscription_identifier
     *           The identifier of the subscription query this is a response for 
     *     @type \Io\Axoniq\Axonserver\Grpc\Query\QueryResponse $initial_result
     *           Provides an Initial Response 
     *     @type \Io\Axoniq\Axonserver\Grpc\Query\QueryUpdate $update
     *           Provides an Update Response 
     *     @type \Io\Axoniq\Axonserver\Grpc\Query\QueryUpdateComplete $complete
     *           Indicates the Query is complete, and no more Updates will be sent 
     *     @type \Io\Axoniq\Axonserver\Grpc\Query\QueryUpdateCompleteExceptionally $complete_exceptionally
     *           Indicates the Query failed exceptionally, and no more Updates will be sent 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique identifier for this message 
     *
     * Generated from protobuf field <code>string message_identifier = 1;</code>
     * @return string
     */
    public function getMessageIdentifier()
    {
        return $this->message_identifier;
    }

    /**
     * The unique identifier for this message 
     *
     * Generated from protobuf field <code>string message_identifier = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->message_identifier = $var;

        return $this;
    }

    /**
     * The identifier of the subscription query this is a response for 
     *
     * Generated from protobuf field <code>string subscription_identifier = 2;</code>
     * @return string
     */
    public function getSubscriptionIdentifier()
    {
        return $this->subscription_identifier;
    }

    /**
     * The identifier of the subscription query this is a response for 
     *
     * Generated from protobuf field <code>string subscription_identifier = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSubscriptionIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->subscription_identifier = $var;

        return $this;
    }

    /**
     * Provides an Initial Response 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.query.QueryResponse initial_result = 3;</code>
     * @return \Io\Axoniq\Axonserver\Grpc\Query\QueryResponse
     */
    public function getInitialResult()
    {
        return $this->readOneof(3);
    }

    /**
     * Provides an Initial Response 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.query.QueryResponse initial_result = 3;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\Query\QueryResponse $var
     * @return $this
     */
    public function setInitialResult($var)
    {
        GPBUtil::checkMessage($var, \Io\Axoniq\Axonserver\Grpc\Query\QueryResponse::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Provides an Update Response 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.query.QueryUpdate update = 4;</code>
     * @return \Io\Axoniq\Axonserver\Grpc\Query\QueryUpdate
     */
    public function getUpdate()
    {
        return $this->readOneof(4);
    }

    /**
     * Provides an Update Response 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.query.QueryUpdate update = 4;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\Query\QueryUpdate $var
     * @return $this
     */
    public function setUpdate($var)
    {
        GPBUtil::checkMessage($var, \Io\Axoniq\Axonserver\Grpc\Query\QueryUpdate::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Indicates the Query is complete, and no more Updates will be sent 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.query.QueryUpdateComplete complete = 5;</code>
     * @return \Io\Axoniq\Axonserver\Grpc\Query\QueryUpdateComplete
     */
    public function getComplete()
    {
        return $this->readOneof(5);
    }

    /**
     * Indicates the Query is complete, and no more Updates will be sent 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.query.QueryUpdateComplete complete = 5;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\Query\QueryUpdateComplete $var
     * @return $this
     */
    public function setComplete($var)
    {
        GPBUtil::checkMessage($var, \Io\Axoniq\Axonserver\Grpc\Query\QueryUpdateComplete::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Indicates the Query failed exceptionally, and no more Updates will be sent 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.query.QueryUpdateCompleteExceptionally complete_exceptionally = 6;</code>
     * @return \Io\Axoniq\Axonserver\Grpc\Query\QueryUpdateCompleteExceptionally
     */
    public function getCompleteExceptionally()
    {
        return $this->readOneof(6);
    }

    /**
     * Indicates the Query failed exceptionally, and no more Updates will be sent 
     *
     * Generated from protobuf field <code>.io.axoniq.axonserver.grpc.query.QueryUpdateCompleteExceptionally complete_exceptionally = 6;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\Query\QueryUpdateCompleteExceptionally $var
     * @return $this
     */
    public function setCompleteExceptionally($var)
    {
        GPBUtil::checkMessage($var, \Io\Axoniq\Axonserver\Grpc\Query\QueryUpdateCompleteExceptionally::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getResponse()
    {
        return $this->whichOneof("response");
    }

}

