<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Io\Axoniq\Axonserver\Grpc\Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Message containing the names of the columns returned in a Query 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.event.ColumnsResponse</code>
 */
class ColumnsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The names of the columns provided in the query 
     *
     * Generated from protobuf field <code>repeated string column = 1;</code>
     */
    private $column;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $column
     *           The names of the columns provided in the query 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * The names of the columns provided in the query 
     *
     * Generated from protobuf field <code>repeated string column = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getColumn()
    {
        return $this->column;
    }

    /**
     * The names of the columns provided in the query 
     *
     * Generated from protobuf field <code>repeated string column = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setColumn($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->column = $arr;

        return $this;
    }

}

