<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Io\Axoniq\Axonserver\Grpc\Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request message to retrieve Snapshot Events for a specific Aggregate instance 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.event.GetAggregateSnapshotsRequest</code>
 */
class GetAggregateSnapshotsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The identifier to fetch the snapshots for 
     *
     * Generated from protobuf field <code>string aggregate_id = 1;</code>
     */
    private $aggregate_id = '';
    /**
     * The minimal sequence number of the snapshots to retrieve 
     *
     * Generated from protobuf field <code>int64 initial_sequence = 2;</code>
     */
    private $initial_sequence = 0;
    /**
     * The maximum sequence number of the snapshots to retrieve 
     *
     * Generated from protobuf field <code>int64 max_sequence = 3;</code>
     */
    private $max_sequence = 0;
    /**
     * The maximum number of results to stream 
     *
     * Generated from protobuf field <code>int32 max_results = 4;</code>
     */
    private $max_results = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $aggregate_id
     *           The identifier to fetch the snapshots for 
     *     @type int|string $initial_sequence
     *           The minimal sequence number of the snapshots to retrieve 
     *     @type int|string $max_sequence
     *           The maximum sequence number of the snapshots to retrieve 
     *     @type int $max_results
     *           The maximum number of results to stream 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * The identifier to fetch the snapshots for 
     *
     * Generated from protobuf field <code>string aggregate_id = 1;</code>
     * @return string
     */
    public function getAggregateId()
    {
        return $this->aggregate_id;
    }

    /**
     * The identifier to fetch the snapshots for 
     *
     * Generated from protobuf field <code>string aggregate_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAggregateId($var)
    {
        GPBUtil::checkString($var, True);
        $this->aggregate_id = $var;

        return $this;
    }

    /**
     * The minimal sequence number of the snapshots to retrieve 
     *
     * Generated from protobuf field <code>int64 initial_sequence = 2;</code>
     * @return int|string
     */
    public function getInitialSequence()
    {
        return $this->initial_sequence;
    }

    /**
     * The minimal sequence number of the snapshots to retrieve 
     *
     * Generated from protobuf field <code>int64 initial_sequence = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInitialSequence($var)
    {
        GPBUtil::checkInt64($var);
        $this->initial_sequence = $var;

        return $this;
    }

    /**
     * The maximum sequence number of the snapshots to retrieve 
     *
     * Generated from protobuf field <code>int64 max_sequence = 3;</code>
     * @return int|string
     */
    public function getMaxSequence()
    {
        return $this->max_sequence;
    }

    /**
     * The maximum sequence number of the snapshots to retrieve 
     *
     * Generated from protobuf field <code>int64 max_sequence = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxSequence($var)
    {
        GPBUtil::checkInt64($var);
        $this->max_sequence = $var;

        return $this;
    }

    /**
     * The maximum number of results to stream 
     *
     * Generated from protobuf field <code>int32 max_results = 4;</code>
     * @return int
     */
    public function getMaxResults()
    {
        return $this->max_results;
    }

    /**
     * The maximum number of results to stream 
     *
     * Generated from protobuf field <code>int32 max_results = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxResults($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_results = $var;

        return $this;
    }

}

