<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Io\Axoniq\Axonserver\Grpc\Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request message to receive the Token that starts streaming events from the given timestamp 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.event.GetTokenAtRequest</code>
 */
class GetTokenAtRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Timestamp expressed as milliseconds since epoch 
     *
     * Generated from protobuf field <code>int64 instant = 1;</code>
     */
    private $instant = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $instant
     *           Timestamp expressed as milliseconds since epoch 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * Timestamp expressed as milliseconds since epoch 
     *
     * Generated from protobuf field <code>int64 instant = 1;</code>
     * @return int|string
     */
    public function getInstant()
    {
        return $this->instant;
    }

    /**
     * Timestamp expressed as milliseconds since epoch 
     *
     * Generated from protobuf field <code>int64 instant = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInstant($var)
    {
        GPBUtil::checkInt64($var);
        $this->instant = $var;

        return $this;
    }

}

