<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Io\Axoniq\Axonserver\Grpc\Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Description of a Payload Type 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.event.PayloadDescription</code>
 */
class PayloadDescription extends \Google\Protobuf\Internal\Message
{
    /**
     * The type identifier of the Payload 
     *
     * Generated from protobuf field <code>string type = 1;</code>
     */
    private $type = '';
    /**
     * The revision of the Payload Type 
     *
     * Generated from protobuf field <code>string revision = 2;</code>
     */
    private $revision = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *           The type identifier of the Payload 
     *     @type string $revision
     *           The revision of the Payload Type 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * The type identifier of the Payload 
     *
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * The type identifier of the Payload 
     *
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * The revision of the Payload Type 
     *
     * Generated from protobuf field <code>string revision = 2;</code>
     * @return string
     */
    public function getRevision()
    {
        return $this->revision;
    }

    /**
     * The revision of the Payload Type 
     *
     * Generated from protobuf field <code>string revision = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRevision($var)
    {
        GPBUtil::checkString($var, True);
        $this->revision = $var;

        return $this;
    }

}

