<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Io\Axoniq\Axonserver\Grpc\Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The highest Sequence Number found for the provided request
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.event.ReadHighestSequenceNrResponse</code>
 */
class ReadHighestSequenceNrResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The sequence number of the latest event 
     *
     * Generated from protobuf field <code>int64 to_sequence_nr = 1;</code>
     */
    private $to_sequence_nr = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $to_sequence_nr
     *           The sequence number of the latest event 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * The sequence number of the latest event 
     *
     * Generated from protobuf field <code>int64 to_sequence_nr = 1;</code>
     * @return int|string
     */
    public function getToSequenceNr()
    {
        return $this->to_sequence_nr;
    }

    /**
     * The sequence number of the latest event 
     *
     * Generated from protobuf field <code>int64 to_sequence_nr = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setToSequenceNr($var)
    {
        GPBUtil::checkInt64($var);
        $this->to_sequence_nr = $var;

        return $this;
    }

}

