<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Io\Axoniq\Axonserver\Grpc\Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Describes the combination of an Aggregate Identifier and first expected Sequence number when opening an Aggregate-specific Event Stream 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.event.ReadHighestSequenceNrRequest</code>
 */
class ReadHighestSequenceNrRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The Identifier of the Aggregate for which to load events 
     *
     * Generated from protobuf field <code>string aggregate_id = 1;</code>
     */
    private $aggregate_id = '';
    /**
     * The Sequence Number of the first event expected 
     *
     * Generated from protobuf field <code>int64 from_sequence_nr = 3;</code>
     */
    private $from_sequence_nr = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $aggregate_id
     *           The Identifier of the Aggregate for which to load events 
     *     @type int|string $from_sequence_nr
     *           The Sequence Number of the first event expected 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * The Identifier of the Aggregate for which to load events 
     *
     * Generated from protobuf field <code>string aggregate_id = 1;</code>
     * @return string
     */
    public function getAggregateId()
    {
        return $this->aggregate_id;
    }

    /**
     * The Identifier of the Aggregate for which to load events 
     *
     * Generated from protobuf field <code>string aggregate_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAggregateId($var)
    {
        GPBUtil::checkString($var, True);
        $this->aggregate_id = $var;

        return $this;
    }

    /**
     * The Sequence Number of the first event expected 
     *
     * Generated from protobuf field <code>int64 from_sequence_nr = 3;</code>
     * @return int|string
     */
    public function getFromSequenceNr()
    {
        return $this->from_sequence_nr;
    }

    /**
     * The Sequence Number of the first event expected 
     *
     * Generated from protobuf field <code>int64 from_sequence_nr = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFromSequenceNr($var)
    {
        GPBUtil::checkInt64($var);
        $this->from_sequence_nr = $var;

        return $this;
    }

}

