<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Io\Axoniq\Axonserver\Grpc\Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Message providing Query Result data 
 *
 * Generated from protobuf message <code>io.axoniq.axonserver.grpc.event.RowResponse</code>
 */
class RowResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The values which, when combined, uniquely update this row. Any previously received values with the same identifiers should be replaced with this value 
     *
     * Generated from protobuf field <code>repeated .io.axoniq.axonserver.grpc.event.QueryValue id_values = 1;</code>
     */
    private $id_values;
    /**
     * The sorting values to use when sorting this response compared to the others. 
     *
     * Generated from protobuf field <code>repeated .io.axoniq.axonserver.grpc.event.QueryValue sort_values = 2;</code>
     */
    private $sort_values;
    /**
     * The actual data values for each of the columns, as a column name -> value mapping 
     *
     * Generated from protobuf field <code>map<string, .io.axoniq.axonserver.grpc.event.QueryValue> values = 3;</code>
     */
    private $values;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Axoniq\Axonserver\Grpc\Event\QueryValue[]|\Google\Protobuf\Internal\RepeatedField $id_values
     *           The values which, when combined, uniquely update this row. Any previously received values with the same identifiers should be replaced with this value 
     *     @type \Io\Axoniq\Axonserver\Grpc\Event\QueryValue[]|\Google\Protobuf\Internal\RepeatedField $sort_values
     *           The sorting values to use when sorting this response compared to the others. 
     *     @type array|\Google\Protobuf\Internal\MapField $values
     *           The actual data values for each of the columns, as a column name -> value mapping 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * The values which, when combined, uniquely update this row. Any previously received values with the same identifiers should be replaced with this value 
     *
     * Generated from protobuf field <code>repeated .io.axoniq.axonserver.grpc.event.QueryValue id_values = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIdValues()
    {
        return $this->id_values;
    }

    /**
     * The values which, when combined, uniquely update this row. Any previously received values with the same identifiers should be replaced with this value 
     *
     * Generated from protobuf field <code>repeated .io.axoniq.axonserver.grpc.event.QueryValue id_values = 1;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\Event\QueryValue[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIdValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Axoniq\Axonserver\Grpc\Event\QueryValue::class);
        $this->id_values = $arr;

        return $this;
    }

    /**
     * The sorting values to use when sorting this response compared to the others. 
     *
     * Generated from protobuf field <code>repeated .io.axoniq.axonserver.grpc.event.QueryValue sort_values = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSortValues()
    {
        return $this->sort_values;
    }

    /**
     * The sorting values to use when sorting this response compared to the others. 
     *
     * Generated from protobuf field <code>repeated .io.axoniq.axonserver.grpc.event.QueryValue sort_values = 2;</code>
     * @param \Io\Axoniq\Axonserver\Grpc\Event\QueryValue[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSortValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Axoniq\Axonserver\Grpc\Event\QueryValue::class);
        $this->sort_values = $arr;

        return $this;
    }

    /**
     * The actual data values for each of the columns, as a column name -> value mapping 
     *
     * Generated from protobuf field <code>map<string, .io.axoniq.axonserver.grpc.event.QueryValue> values = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * The actual data values for each of the columns, as a column name -> value mapping 
     *
     * Generated from protobuf field <code>map<string, .io.axoniq.axonserver.grpc.event.QueryValue> values = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setValues($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Axoniq\Axonserver\Grpc\Event\QueryValue::class);
        $this->values = $arr;

        return $this;
    }

}

